name: Build

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  # Build image
  build-base-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mamba: [latest, 1.4.0]
        cuda: [120, 121]
        flavor: [runtime, devel]
        ubuntu: [20.04, 22.04]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build base image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "./base"
          file: "./base/Dockerfile.cuda"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mambabase:${{ matrix.mamba }}-cu${{ matrix.cuda }}-${{ matrix.flavor }}-ubuntu${{ matrix.ubuntu }}
          build-args: |
            MAMBA=${{ matrix.mamba }}
            CUDA=${{ matrix.cuda }}
            FLAVOR=${{ matrix.flavor }}
            USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            UBUNTU=${{ matrix.ubuntu }}

  build-book-image:
    needs: build-base-image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mamba: [latest, 1.4.0]
        cuda: [120, 121]
        flavor: [runtime, devel]
        ubuntu: [20.04, 22.04]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build book image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "./book"
          file: "./book/Dockerfile.cuda"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mambabook:${{ matrix.mamba }}-cu${{ matrix.cuda }}-${{ matrix.flavor }}-ubuntu${{ matrix.ubuntu }}
          build-args: |
            MAMBA=${{ matrix.mamba }}
            CUDA=${{ matrix.cuda }}
            FLAVOR=${{ matrix.flavor }}
            USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            UBUNTU=${{ matrix.ubuntu }}
