name: Build

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  # Build image
  build-cuda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cuda: [112, 113, 114, 116, 118, 120]
        flavor: [runtime, devel]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build base image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "./base"
          file: "./base/Dockerfile.cuda"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mambabase:cu${{ matrix.cuda }}-${{ matrix.flavor }}
          build-args: |
            CUDA=${{ matrix.cuda }}
            FLAVOR=${{ matrix.flavor }}
            USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "./book"
          file: "./book/Dockerfile.cuda"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mambabook:cu${{ matrix.cuda }}-${{ matrix.flavor }}
          build-args: |
            CUDA=${{ matrix.cuda }}
            FLAVOR=${{ matrix.flavor }}
            USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
